# Site settings
title: SHOFCO's Mixed Income International School
email: elaurits@shofco.com
description: A world class international school for change makers by change makers.
baseurl: "/spectral-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url:
instagram_url: https://www.instagram.com/shofco_sankore
linkedin_url: https://www.linkedin.com/company/shofco/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
